// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDmaaCOeH5BLuKkC8JwRIY4bxLUNGNRrY',
    appId: '1:123281224453:web:e870a884ad72393852fd6c',
    messagingSenderId: '123281224453',
    projectId: 'user-561fd',
    authDomain: 'user-561fd.firebaseapp.com',
    storageBucket: 'user-561fd.firebasestorage.app',
    measurementId: 'G-5PZ1TLWJX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6OqbPTxoScJ2-St19PL1ZCsdgW7qldGE',
    appId: '1:123281224453:android:8ff4716acf07325552fd6c',
    messagingSenderId: '123281224453',
    projectId: 'user-561fd',
    storageBucket: 'user-561fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KeTsE-NR-RawXbT4_Uq0_IWAE4c4l_Q',
    appId: '1:123281224453:ios:b7f57a3b9452a3de52fd6c',
    messagingSenderId: '123281224453',
    projectId: 'user-561fd',
    storageBucket: 'user-561fd.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KeTsE-NR-RawXbT4_Uq0_IWAE4c4l_Q',
    appId: '1:123281224453:ios:b7f57a3b9452a3de52fd6c',
    messagingSenderId: '123281224453',
    projectId: 'user-561fd',
    storageBucket: 'user-561fd.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDmaaCOeH5BLuKkC8JwRIY4bxLUNGNRrY',
    appId: '1:123281224453:web:fd9e1c2f1465da8152fd6c',
    messagingSenderId: '123281224453',
    projectId: 'user-561fd',
    authDomain: 'user-561fd.firebaseapp.com',
    storageBucket: 'user-561fd.firebasestorage.app',
    measurementId: 'G-DPX1DW0PWJ',
  );
}
